### ISSUE TITLE
$sort descending

### ISSUE THREAD

**Issue by christianbundy** [dominictarr/ssb-query#14]
I'm using ssb-query (flumeview-query / map-filter-reduce) and sorting messages by their received timestamp, but I need these messages to be sorted *descending*, with the latest messages showing first. Here's what I have right now:

```
195     const query = [{ 
196       $filter: {
197         dest: myFeedId
198       },
199     }, {
200       $sort: ['timestamp'] 
201     }]
```

How can I change the sort direction? I've checked the readme for each of the three repos but haven't found any info.

**Comment by dominictarr** [comment]
I've never used that, but turns out I did implement it: https://www.npmjs.com/package/compare-at-paths (which map-filter-reduce depends on) `$sort: {$reverse:['timestamp']}`

**Comment by christianbundy** [comment]
Awesome, thank you!
